Added --quiet option to suppress no issues
PyCQA/autoflake pull request #89
Opened 2021-04-27 12:06 UTC by EdvardM

2022-02-15 20:33 UTC, BenQuigley requested changes

2022-02-15 20:33 UTC, BenQuigley commented on autoflake.py
> +        if args.check and not args.quiet:
This line is going to evaluate to `False` if the user does not pass `--quiet`, which is going to result in the `else` statement printing "Clean foo.py: nothing to fix". Instead, consider:
```
         if args.check:                                 
-            standard_out.write('No issues detected!\n')                                                                                                      
+            if not args.quiet:                                                                                                                               
+                standard_out.write('No issues detected!\n')                                                                                                  
         else:                                                                
             _LOGGER.debug('Clean %s: nothing to fix', filename)
```

2022-02-15 20:41 UTC, BenQuigley commented
Good PR; it would be good to merge this. In the meantime I'm stuck running `autoflake --check > /dev/null` to suppress the stdout output. (Actually I think the quiet mode should be the default, and 'no problem' should only be logged if running with verbosity >= 1.)

2022-02-23 14:01 UTC, edvardm commented
> Good PR; it would be good to merge this. In the meantime I'm stuck running `autoflake --check > /dev/null` to suppress the stdout output. (Actually I think the quiet mode should be the default, and 'no problem' should only be logged if running with verbosity >= 1.)

Agreed, this was a quick fix. 

However, this project seems to be abandoned :( Or author is just too busy -- which is quite understandable. If that's the case, it would be great to have this information in README.md

2022-08-24 04:48 UTC, fsouza approved these changes
Thanks for contributing!

2022-08-24 04:48 UTC, merged